"""rename order model fields

Revision ID: 0fde739396dc
Revises: e60a1fa2a799
Create Date: 2024-10-20 00:02:45.928345

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fde739396dc'
down_revision: str | None = 'e60a1fa2a799'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount_of_shares', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('price_per_share', sa.Numeric(), nullable=False))
    op.drop_column('order', 'price')
    op.drop_column('order', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('order', 'price_per_share')
    op.drop_column('order', 'amount_of_shares')
    # ### end Alembic commands ###
